- name: Configure Catalogue Server
  hosts: catalogue
  become: yes

  tasks:
    - name: Disable default Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Create roboshop sytem user
      ansible.builtin.user:
        name: roboshop
        system: yes
        shell: /sbin/nologin
        home: /app

    - name: Download catalogue zip file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Extract catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    
    - name: copy catalogue service to system directory
      ansible.builtin.copy:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable catalogue service
      ansible.builtin.service:
        name: catalogue
        enabled: yes

    - name: start catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started

    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
      
    - name: Install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products are loaded or not
      ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: Load products
      ansible.builtin.shell: mongosh --host mongodb.daws84ss.site < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0