- name: configure shipping component
  hosts: shipping
  become: yes
  tasks: 
    - name: Install maven and mysql
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
      - maven
      - mysql   
      
    - name: Install PyMySQL 
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: Download shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping.zip
        dest: /tmp/shipping.zip

    - name: extract shipping code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Clean and package the Maven application
      ansible.builtin.command: mvn clean package
      args:
            chdir: /app

    - name: Rename the JAR file to shipping.jar
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app    

    - name: Copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: systemctl deamon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable and start shipping
      ansible.builtin.service:
        name: shipping
        enabled: yes
        state: started

    # - name: connect to mysql using app user
    #   community.mysql.mysql_info:
    #     login_user: shipping
    #     login_password: RoboShop@1
    #     login_host: mysql.daws.84ss.site
    #     login_db: cities

    - name: import data 
      community.mysql.mysql_db:
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.daws.84ss.site
        state: import
        target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

    - name: Restart shipping service
      ansible.builtin.systemd:
        name: shipping
        state: restarted

